include(../guie.pri)
TEMPLATE = app
DESTDIR = $$GUIE_APP_PATH

QMAKE_CXXFLAGS_RELEASE = $$QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO
QMAKE_LFLAGS_RELEASE = $$QMAKE_LFLAGS_RELEASE_WITH_DEBUGINFO

target.path = $$INSTALL_PREFIX/bin/guie
INSTALLS += target
